config/routes.rb
Rails.application.routes.draw do
  root :to => 'r3log#top'
  get 'about' => "r3log#about"
  get 'howto' => 'r3log#howto'

  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get  '/logout',  to: 'sessions#destroy'

  post '/api/new', to: 'api#create'
  get '/api/top', to: 'api#gettop'
  get '/api/rank', to: 'api#getrank'
  get '/api/status', to: 'api#getstatus'
  get '/api/util', to: 'api#getutil'

  resources :stats, only: [:logs, :nw_d, :nw_s, :ow_d, :ow_s] do
    collection do
      get :logs
      get :nw_d
      get :nw_s
      get :ow_d
      get :ow_s
      get :dma
    end
  end

  resources :admin, only: [:season] do
    collection do
      get :season, to: 'admin#season'
      post :season, to: 'admin#new_season'
    end
    member do
      delete :season, to: 'admin#delete_season'
      get "season/edit", to: 'admin#edit_season'
      post "season/edit", to: 'admin#update_season'
    end
  end

  resources :users, param: :id, only: [:index, :show] do
    collection do
      get :index
    end
    member do
      get :show, to: "users#show"
      post :show, to: "users#rename"
      delete :show, to: "users#delete"
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/views/admin/_permission_error.html.erb
<h2>権限エラー</h2>
<p>このページは管理者権限が必要です。</p>

app/views/admin/edit.turbo_stream.erb
<%= turbo_stream.append "modal" do %>
  <div class="modal" tabindex="-1" data-controller="modal" data-bs-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= t "season.modal_edit" %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= form_with url: season_edit_admin_path(id: params[:id]), method: :post, data: {turbo:false} do |f| %>
          <div class="modal-body">
            <%= f.text_area :message , class: 'col-form-label', placeholder: (t "season.message"), style: "width:100%", rows: "3" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t "close" %></button>
            <%= f.submit (t "confirm"), class: 'btn btn-primary' %>
          </div>
        <% end %> 
      </div>
    </div>
  </div>
<% end %>

app/views/admin/season.html.erb
<% if logged_in? %>
  <h3><%= t "nav.season" %></h3>
  <div class="mt-3 mb-3">
    <%= form_for(:season, url: season_admin_index_path) do |f| %>
      <%= f.text_field :name, class: 'col-form-label', placeholder: (t "season.name") %>
      <%= f.submit (t "season.start"), class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th><%= t "name" %></th>
          <th><%= t "season.start_at"%></th>
          <th><%= t "season.finish_at"%></th>
          <th><%= t "season.message"%></th>
          <th><%= t "edit" %>
          <th><%= t "delete" %>
        </tr>
      </thead>
      <tbody>
        <% @seasons.each do |season| %>
          <tr>
            <td><%= season.name %></td>
            <td><%= l season.created_at %></td>
            <td><%= season.finished_at.nil? ? "" : (l season.finished_at) %></td>
            <td><%= season.message %></td>
            <td><%= button_to (t "edit"), season_edit_admin_path(id: season.id), {method: :get, class: 'btn btn-primary', data: { turbo_stream: true }} %></td>
            <td><%= button_to (t "delete"), season_admin_path(id: season.id), {method: :delete, data: {turbo_confirm: (t "season.confirm")}, class: 'btn btn-danger'} %></td>         
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <%= render 'admin/permission_error' %>
<% end %>