config/routes.rb
Rails.application.routes.draw do
  root :to => 'r3log#top'
  get 'about' => "r3log#about"
  get 'howto' => 'r3log#howto'

  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get  '/logout',  to: 'sessions#destroy'

  post '/api/new', to: 'api#create'
  get '/api/top', to: 'api#gettop'
  get '/api/rank', to: 'api#getrank'
  get '/api/status', to: 'api#getstatus'
  get '/api/util', to: 'api#getutil'

  resources :stats, only: [:logs, :nw_d, :nw_s, :ow_d, :ow_s] do
    collection do
      get :logs
      get :nw_d
      get :nw_s
      get :ow_d
      get :ow_s
      get :dma
    end
  end

  resources :admin, only: [:season] do
    collection do
      get :season, to: 'admin#season'
      post :season, to: 'admin#new_season'
    end
    member do
      delete :season, to: 'admin#delete_season'
      get "season/edit", to: 'admin#edit_season'
      post "season/edit", to: 'admin#update_season'
    end
  end

  resources :users, param: :id, only: [:index, :show] do
    collection do
      get :index
    end
    member do
      get :show, to: "users#show"
      post :show, to: "users#rename"
      delete :show, to: "users#delete"
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def nw_s
    @season = params[:season].blank? || params[:season][:season].blank? ? Season.find_by(finished_at: nil) : Season.find_by(id: params[:season][:season])
    @stats = @season.users.where.not(nw_s_win: 0, nw_s_lose: 0).order(nw_s_rate: :desc, nw_s_win: :desc, updated_at: :asc).page(params[:page])
  end

  def nw_d
    @season = params[:season].blank? || params[:season][:season].blank? ? Season.find_by(finished_at: nil) : Season.find_by(id: params[:season][:season])
    @stats = @season.users.where.not(nw_d_win: 0, nw_d_lose: 0).order(nw_d_rate: :desc, nw_d_win: :desc, updated_at: :asc).page(params[:page])
  end

  def ow_s
    @season = params[:season].blank? || params[:season][:season].blank? ? Season.find_by(finished_at: nil) : Season.find_by(id: params[:season][:season])
    @stats = @season.users.where.not(ow_s_win: 0, ow_s_lose: 0).order(ow_s_rate: :desc, ow_s_win: :desc, updated_at: :asc).page(params[:page])
  end

  def ow_d
    @season = params[:season].blank? || params[:season][:season].blank? ? Season.find_by(finished_at: nil) : Season.find_by(id: params[:season][:season])
    @stats = @season.users.where.not(ow_d_win: 0, ow_d_lose: 0).order(ow_d_rate: :desc, ow_d_win: :desc, updated_at: :asc).page(params[:page])
  end

  def dma
    @season = params[:season].blank? || params[:season][:season].blank? ? Season.find_by(finished_at: nil) : Season.find_by(id: params[:season][:season])
    @stats = @season.users.where.not(dma_win: 0, dma_lose: 0).order(dma_rate: :desc, dma_win: :desc, updated_at: :asc).page(params[:page])
  end
  
  def logs
    @season = params[:q].blank? || params[:q][:season].blank? ? Season.find_by(finished_at: nil) : Season.find_by(id: params[:q][:season])
    @q = @season.matches.ransack(params[:q])
    @logs = @q.result.order(created_at: :desc).page(params[:page])
  end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/dma.html.erb
<p class="h2"><%= t "rule.dma" %> <%= t "stats.rank_title" %></p>
<br>
<div class="accordion mb-3" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= t "season.select" %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= form_for :season, url: dma_stats_path, method: :get do |f| %>
          <div class="row g-4 mb-3">
            <div class="col-auto">
              <%= f.select :season, Season.all.map{|s| [s.name, s.id]}, {selected: @season.id}, {class: "form-control col-6"} %>
            </div>    
            <div class="col-auto">
              <%= f.submit (t "season.view"), class: 'btn btn-primary' %>
            </div>
            <div class="col-auto">
              <%= link_to (t "season.reset"), dma_stats_path(@page), class: "btn btn-outline-secondary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t "stats.rank" %></th>
        <th><%= t "name" %></th>
        <th><%= t "stats.rate" %></th>
        <th><%= t "stats.win" %></th>
        <th><%= t "stats.lose" %></th>
        <th><%= t "stats.win_p" %></th>
      </tr>
    </thead>
    <tbody>
      <% rank = @page ? (@page - 1) * Kaminari.configure.default_per_page + 1 : 1 %>
      <% @stats.each do |stats| %>
        <tr class="clickable-row" data-href="<%= user_path(id: stats) %>">
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= rank %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.name %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.dma_rate %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.dma_win %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.dma_lose %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.dma_lose != 0 ? (stats.dma_win.to_f / (stats.dma_win.to_f + stats.dma_lose.to_f) * 100).round(2) : 100 %>%</td>
        </tr>
        <% rank += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @stats, theme: 'bootstrap-5'  %>

<style scoped>
tbody tr:hover {
    background-color:#a9ceec ;
}
</style>

<script type="module">
  $(function($) {
    $(".clickable-row").css("cursor","pointer").click(function() {
      location.href = $(this).data("href")
    });
  });
</script>

app/views/stats/logs.html.erb
<p class="h2"><%= t "stats.log_title" %></p>
<br>

<div class="accordion mb-3" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= t "search.title" %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= search_form_for @q, url: logs_stats_path do |f| %>
          <div class="row g-4 mb-3">
            <div class="col-auto">
              <%= f.search_field :redname1_or_redname2_or_bluename1_or_bluename2_cont, class: 'col-form-label', placeholder: 'ユーザー名' %>
            </div>    
            <div class="col-auto">
              <%= f.submit (t "search.submit"), class: 'btn btn-primary' %>
            </div>
            <div class="col-auto">
              <%= link_to (t "search.reset"), logs_stats_path(@page), class: "btn btn-outline-secondary" %>
            </div>
          </div>
          <label><%= t "stats.season" %></label>
          <div class="mb-3">
            <%= f.select :season, Season.all.map{|s| [s.name, s.id]}, {selected: @season.id}, {class: "form-control col-6"} %>
          </div>
          <label><%= t "rule.rule" %></label>
          <div class=".d-flex">
            <%= f.check_box :hopping_allowed_eq_any, { multiple: true, include_hidden: false }, true %>
            <label><%= t "stats.jump_on" %></label>
            <%= f.check_box :hopping_allowed_eq_any, { multiple: true, include_hidden: false }, false %>
            <label><%= t "stats.jump_off" %></label>
          </div>
          <div class=".d-flex">
            <%= f.check_box :game_double_eq_any, { multiple: true, include_hidden: false }, true %>
            <label><%= t "rule.double" %></label>
            <%= f.check_box :game_double_eq_any, { multiple: true, include_hidden: false }, false %>
            <label><%= t "rule.single" %></label>
          </div>
          <div class=".d-flex">
            <%= f.check_box :game_boundaries_eq_any, { multiple: true, include_hidden: false }, true %>
            <label><%= t "rule.no_wall" %></label>
            <%= f.check_box :game_boundaries_eq_any, { multiple: true, include_hidden: false }, false %>
            <label><%= t "rule.no_wall" %></label>
          </div>
          <div class=".d-flex mb-3">
            <%= f.check_box :score_max_eq_any, { multiple: true, include_hidden: false }, "1" %>
            <label>1<%= t "stats.point" %></label>
            <%= f.check_box :score_max_eq_any, { multiple: true, include_hidden: false }, "5" %>
            <label>5<%= t "stats.point" %></label>
            <%= f.check_box :score_max_eq_any, { multiple: true, include_hidden: false }, "10" %>
            <label>10<%= t "stats.point" %></label>
          </div>
          <label><%= t "stats.ex" %></label>
          <div class=".d-flex">
            <%= f.check_box :game_ex_speed_eq_any, { multiple: true, include_hidden: false }, "off" %>
            <label><%= t "stats.ex_off" %></label>
            <%= f.check_box :game_ex_speed_eq_any, { multiple: true, include_hidden: false }, "ex1" %>
            <label><%= t "stats.ex_1" %></label>
            <%= f.check_box :game_ex_speed_eq_any, { multiple: true, include_hidden: false }, "ex2" %>
            <label><%= t "stats.ex_2" %></label>
          </div>
          <label><%= t "rule.dma" %></label>
          <div class=".d-flex">
            <%= f.check_box :dma_eq_any, { multiple: true, include_hidden: false }, true %>
            <label><%= t "stats.dma.on" %></label>
            <%= f.check_box :dma_eq_any, { multiple: true, include_hidden: false }, false %>
            <label><%= t "stats.dma.off" %></label>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div>
  <table class="table mb-3">
    <thead>
      <tr>
        <th><%= t "stats.time" %></th>
        <th><%= t "stats.red1" %></th>
        <th><%= t "stats.red_score" %></th>
        <th><%= t "stats.red_rate" %></th>
        <th><%= t "stats.blue1" %></th>
        <th><%= t "stats.blue_score" %></th>
        <th><%= t "stats.blue_rate" %></th>
        <th><%= t "stats.winner" %></th>
        <th><%= t "stats.rule" %></th>
        <th><%= t "stats.jump" %></th>
        <th><%= t "stats.ex" %></th>
        <th><%= t "rule.dma" %></th>
      </tr>
    </thead>
    <tbody>
      <% @logs.each do |logs| %>
        <tr>
          <td><%= l logs.created_at %></td>
          <td><%= logs.redname1 %></td>
          <td><%= logs.redscore %></td>
          <td><%= logs.reddiff1 %></td>

          <td><%= logs.bluename1 %></td>
          <td><%= logs.bluescore %></td>
          <td><%= logs.bluediff1 %></td>

          <td><%= logs.winner1 %></td>

          <td><%= logs.game_boundaries ? (t "rule.on_wall") : (t "rule.no_wall") %><%= logs.game_double ? (t "rule.double") : (t "rule.single") %><%= logs.score_max %><%= t "stats.point" %></td>
          <td><%= logs.hopping_allowed ? "ON" : "OFF" %></td>
          <td><%= logs.game_ex_speed %></td>
          <td><%= logs.dma ? "ON" : "OFF" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="mb-3">
  <%= paginate @logs, theme: 'bootstrap-5'  %>
</div>

app/views/stats/nw_d.html.erb
<p class="h2"><%= t "rule.no_wall_double" %> <%= t "stats.rank_title" %></p>
<br>
<div class="accordion mb-3" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= t "season.select" %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= form_for :season, url: nw_d_stats_path, method: :get do |f| %>
          <div class="row g-4 mb-3">
            <div class="col-auto">
              <%= f.select :season, Season.all.map{|s| [s.name, s.id]}, {selected: @season.id}, {class: "form-control col-6"} %>
            </div>    
            <div class="col-auto">
              <%= f.submit (t "season.view"), class: 'btn btn-primary' %>
            </div>
            <div class="col-auto">
              <%= link_to (t "season.reset"), nw_d_stats_path(@page), class: "btn btn-outline-secondary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t "stats.rank" %></th>
        <th><%= t "name" %></th>
        <th><%= t "stats.rate" %></th>
        <th><%= t "stats.win" %></th>
        <th><%= t "stats.lose" %></th>
        <th><%= t "stats.win_p" %></th>
      </tr>
    </thead>
    <tbody>
      <% rank = @page ? (@page - 1) * Kaminari.configure.default_per_page + 1 : 1 %>
      <% @stats.each do |stats| %>
        <tr class="clickable-row" data-href="<%= user_path(id: stats) %>">
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= rank %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.name %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_d_rate %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_d_win %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_d_lose %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_d_lose != 0 ? (stats.nw_d_win.to_f / (stats.nw_d_win.to_f + stats.nw_d_lose.to_f) * 100).round(2) : 100 %>%</td>
        </tr>
        <% rank += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @stats, theme: 'bootstrap-5'  %>

<style scoped>
tbody tr:hover {
    background-color:#a9ceec ;
}
</style>

<script type="module">
  $(function($) {
    $(".clickable-row").css("cursor","pointer").click(function() {
      location.href = $(this).data("href")
    });
  });
</script>

app/views/stats/nw_s.html.erb
<p class="h2"><%= t "rule.no_wall_single" %> <%= t "stats.rank_title" %></p>
<br>
<div class="accordion mb-3" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= t "season.select" %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= form_for :season, url: nw_d_stats_path, method: :get do |f| %>
          <div class="row g-4 mb-3">
            <div class="col-auto">
              <%= f.select :season, Season.all.map{|s| [s.name, s.id]}, {selected: @season.id}, {class: "form-control col-6"} %>
            </div>    
            <div class="col-auto">
              <%= f.submit (t "season.view"), class: 'btn btn-primary' %>
            </div>
            <div class="col-auto">
              <%= link_to (t "season.reset"), nw_d_stats_path(@page), class: "btn btn-outline-secondary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t "stats.rank" %></th>
        <th><%= t "name" %></th>
        <th><%= t "stats.rate" %></th>
        <th><%= t "stats.win" %></th>
        <th><%= t "stats.lose" %></th>
        <th><%= t "stats.win_p" %></th>
      </tr>
    </thead>
    <tbody>
      <% rank = @page ? (@page - 1) * Kaminari.configure.default_per_page + 1 : 1 %>
      <% @stats.each do |stats| %>
        <tr class="clickable-row" data-href="<%= user_path(id: stats) %>">
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= rank %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.name %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_s_rate %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_s_win %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_s_lose %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.nw_s_lose != 0 ? (stats.nw_s_win.to_f / (stats.nw_s_win.to_f + stats.nw_s_lose.to_f) * 100).round(2) : 100 %>%</td>
        </tr>
        <% rank += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @stats, theme: 'bootstrap-5'  %>

<style scoped>
tbody tr:hover {
    background-color:#a9ceec ;
}
</style>

<script type="module">
  $(function($) {
    $(".clickable-row").css("cursor","pointer").click(function() {
      location.href = $(this).data("href")
    });
  });
</script>

app/views/stats/ow_d.html.erb
<p class="h2"><%= t "rule.on_wall_double" %> <%= t "stats.rank_title" %></p>
<br>
<div class="accordion mb-3" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= t "season.select" %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= form_for :season, url: nw_d_stats_path, method: :get do |f| %>
          <div class="row g-4 mb-3">
            <div class="col-auto">
              <%= f.select :season, Season.all.map{|s| [s.name, s.id]}, {selected: @season.id}, {class: "form-control col-6"} %>
            </div>    
            <div class="col-auto">
              <%= f.submit (t "season.view"), class: 'btn btn-primary' %>
            </div>
            <div class="col-auto">
              <%= link_to (t "season.reset"), nw_d_stats_path(@page), class: "btn btn-outline-secondary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t "stats.rank" %></th>
        <th><%= t "name" %></th>
        <th><%= t "stats.rate" %></th>
        <th><%= t "stats.win" %></th>
        <th><%= t "stats.lose" %></th>
        <th><%= t "stats.win_p" %></th>
      </tr>
    </thead>
    <tbody>
      <% rank = @page ? (@page - 1) * Kaminari.configure.default_per_page + 1 : 1 %>
      <% @stats.each do |stats| %>
        <tr class="clickable-row" data-href="<%= user_path(id: stats) %>">
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= rank %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.name %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_d_rate %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_d_win %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_d_lose %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_d_lose != 0 ? (stats.ow_d_win.to_f / (stats.ow_d_win.to_f + stats.ow_d_lose.to_f) * 100).round(2) : 100 %>%</td>
        </tr>
        <% rank += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @stats, theme: 'bootstrap-5'  %>

<style scoped>
tbody tr:hover {
    background-color:#a9ceec ;
}
</style>

<script type="module">
  $(function($) {
    $(".clickable-row").css("cursor","pointer").click(function() {
      location.href = $(this).data("href")
    });
  });
</script>

app/views/stats/ow_s.html.erb
<p class="h2"><%= t "rule.on_wall_single" %> <%= t "stats.rank_title" %></p>
<br>
<div class="accordion mb-3" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= t "season.select" %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= form_for :season, url: nw_d_stats_path, method: :get do |f| %>
          <div class="row g-4 mb-3">
            <div class="col-auto">
              <%= f.select :season, Season.all.map{|s| [s.name, s.id]}, {selected: @season.id}, {class: "form-control col-6"} %>
            </div>    
            <div class="col-auto">
              <%= f.submit (t "season.view"), class: 'btn btn-primary' %>
            </div>
            <div class="col-auto">
              <%= link_to (t "season.reset"), nw_d_stats_path(@page), class: "btn btn-outline-secondary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t "stats.rank" %></th>
        <th><%= t "name" %></th>
        <th><%= t "stats.rate" %></th>
        <th><%= t "stats.win" %></th>
        <th><%= t "stats.lose" %></th>
        <th><%= t "stats.win_p" %></th>
      </tr>
    </thead>
    <tbody>
      <% rank = @page ? (@page - 1) * Kaminari.configure.default_per_page + 1 : 1 %>
      <% @stats.each do |stats| %>
        <tr class="clickable-row" data-href="<%= user_path(id: stats) %>">
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= rank %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.name %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_s_rate %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_s_win %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_s_lose %></td>
          <td class="clickable-row" data-href="<%= user_path(id: stats) %>"><%= stats.ow_s_lose != 0 ? (stats.ow_s_win.to_f / (stats.ow_s_win.to_f + stats.ow_s_lose.to_f) * 100).round(2) : 100 %>%</td>
        </tr>
        <% rank += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @stats, theme: 'bootstrap-5'  %>

<style scoped>
tbody tr:hover {
    background-color:#a9ceec ;
}
</style>

<script type="module">
  $(function($) {
    $(".clickable-row").css("cursor","pointer").click(function() {
      location.href = $(this).data("href")
    });
  });
</script>