config/routes.rb
Rails.application.routes.draw do
  root :to => 'r3log#top'
  get 'about' => "r3log#about"
  get 'howto' => 'r3log#howto'

  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get  '/logout',  to: 'sessions#destroy'

  post '/api/new', to: 'api#create'
  get '/api/top', to: 'api#gettop'
  get '/api/rank', to: 'api#getrank'
  get '/api/status', to: 'api#getstatus'
  get '/api/util', to: 'api#getutil'

  resources :stats, only: [:logs, :nw_d, :nw_s, :ow_d, :ow_s] do
    collection do
      get :logs
      get :nw_d
      get :nw_s
      get :ow_d
      get :ow_s
      get :dma
    end
  end

  resources :admin, only: [:season] do
    collection do
      get :season, to: 'admin#season'
      post :season, to: 'admin#new_season'
    end
    member do
      delete :season, to: 'admin#delete_season'
      get "season/edit", to: 'admin#edit_season'
      post "season/edit", to: 'admin#update_season'
    end
  end

  resources :users, param: :id, only: [:index, :show] do
    collection do
      get :index
    end
    member do
      get :show, to: "users#show"
      post :show, to: "users#rename"
      delete :show, to: "users#delete"
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>R3 Log</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <%= turbo_frame_tag 'modal' %>
  <body class="h-100 no-gutters m-0">
    <header class="w-100 d-flex justify-content-between align-items-center px-3 bg-dark border-bottom border-bottom-dark" data-bs-theme="dark" style="height: 60px;">
      <ul class="navbar-nav d-flex flex-row">
        <li class="mx-3 text-muted active"><a href="/" class="nav-link --bs-primary-border-subtle" style="font-size: 20px;">R3 Log</a></li>
      </ul>
      <div class="d-flex flex-row navbar-brand">
        <div class="toggle-menu col-md-5">
          <button class="btn btn-light btn-sm bg-dark" id="toggle"><i class="navbar-toggler-icon"></i></button>
        </div>
      </div>
    </header>
    <div class="d-flex flex-row w-100 justify-content" style="height: calc(100% - 60px)">
      <nav class="bg-secondary " style="width: 200px;">
        <ul class="nav flex-column m-0 p-3">
          <li class="nav-item mb-2">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= nw_s_stats_path %>"><%= t "rule.no_wall_single" %></a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= nw_d_stats_path %>"><%= t "rule.no_wall_double" %></a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= ow_s_stats_path %>"><%= t "rule.on_wall_single" %></a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= ow_d_stats_path %>"><%= t "rule.on_wall_double" %></a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= dma_stats_path %>"><%= t "rule.dma" %></a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= users_path %>"><%= t "nav.users" %></a>
          </li>
          <li class="nav-item mb-2">
            <a class="nav-link" href="<%= logs_stats_path %>"><%= t "nav.logs" %></a>
          </li>
          <% if logged_in? %>
            <li class="nav-item mb-2">
              <a class="nav-link active" aria-current="page" href="<%= season_admin_index_path %>"><%= t "nav.season" %></a>
            </li>
            <li class="nav-item mb-2">
              <br>
            </li>
            <li class="nav-item mb-2">
              <a class="nav-link active" aria-current="page" href="<%= logout_path %>"><%= t "nav.logout" %></a>
            </li>
          <% else %>
            <li class="nav-item mb-2">
              <br>
            </li>
            <li class="nav-item mb-2">
              <a class="nav-link active" aria-current="page" href="<%= login_path %>"><%= t "nav.login" %></a>
            </li>
          <% end %>
          <li class="nav-item mb-2">
            <div class="dropdown col-md-10 .offset-md-4">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= t "language"%>
              </button>
              <ul class="dropdown-menu bg-dark-subtle">
                <li><%= link_to '日本語', url_for(locale: :ja) %></li>
                <li><%= link_to 'English', url_for(locale: :en) %></li>
              </ul>
            </div>
          </li>
        </ul>
      </nav>
      <main class="flex-grow-1 bg-light overflow-y-scroll" style="padding: 10px;">
        <div id="flash">
          <% if flash[:warning] %>
            <div class="alert alert-warning" role="alert"><%= flash[:warning] %></div>
          <% end %>
          <% if flash[:success] %>
            <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
          <% end %>
        </div>
        <%= yield %>
        <br>
      </main>
    </div>
  </body>
  <script type="text/javascript">
    window.onload = () => {
      // toggleボタン
      let sidemenuToggle = document.getElementById('toggle')
      // メインコンテンツを囲むmain要素
      let page = document.getElementsByTagName('main')[0];
      // 表示状態 trueで表示中 falseで非表示
      let sidemenuStatus = true;
      // ボタンクリック時のイベント
      sidemenuToggle.addEventListener('click', () => {
        // 表示状態を判定
        if(sidemenuStatus){
            page.style.cssText = 'margin-left: -200px'
            sidemenuStatus = false;
        }else{
            page.style.cssText = 'margin-left: 0px'
            sidemenuStatus = true;
        }
      })
    }
  </script>  
</html>